### ISSUE TITLE
5.5 version of the book

### ISSUE THREAD

**Issue by emil-nasso** [garyblankenship/leanpub-laravel#1]
Hi!
This is the only way I have found to contact you. :)

I was looking for a way to read the laravel 5.5 documentation on my kindle and I found the book that you (i assume) put together: https://leanpub.com/laravel-5

That book is for 5.4 though. Is there a way to update it for 5.5?

**Comment by garyblankenship** [comment]
It is updated to the latest master branch of the docs.
